<a href="https://colab.research.google.com/github/Migdalia2023/DS_UNI/blob/main/Ejemplo_lectura_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/Migdalia2023/DS_UNI.git

Cloning into 'DS_UNI'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 18 (delta 3), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), 5.78 MiB | 7.51 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('/content/DS_UNI/Salaries.csv')

In [7]:
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116474,116475,Ramon R Dominguez,Construction Inspector,98271.01,25081.75,8033.05,37090.74,131385.81,168476.55,2014.0,NaN,San Francisco,NaN
116475,116476,Evan Mogan,Registered Nurse,111678.04,4916.53,12079.85,39786.42,128674.42,168460.84,2014.0,NaN,San Francisco,NaN
116476,116477,Denise R Green,Transit Supervisor,78435.20,55789.01,2418.05,31807.57,136642.26,168449.83,2014.0,NaN,San Francisco,NaN
116477,116478,Richard F Archibald,EMT/Paramedic/Firefighter,112710.00,11139.77,6145.12,38429.44,129994.89,168424.33,2014.0,NaN,San Francisco,NaN
116478,116479,Justin P Dauterman,Registered Nurse,119314.85,1875.04,8309.64,38.00,NaN,NaN,NaN,NaN,NaN,NaN